from datetime import datetime, timedelta, timezone as datetime_timezone
from zoneinfo import ZoneInfo

from django.contrib.auth.models import User
from django.test import TestCase
from django.urls import reverse
from django.utils import timezone

from apps.matches.models import Match
from apps.matches.management.commands.seed_worldcup_structure import Command as SeedWorldCupCommand
from apps.matches.services import thesportsdb
from apps.predictions.models import Prediction
from apps.predictions.services import recalculate_predictions
from apps.teams.models import Team

from .models import FriendTournament, TournamentMembership
from .services import leaderboard_for_tournament
from . import views


class MvpFlowTests(TestCase):
    def setUp(self):
        self.user = User.objects.create_user('player', 'player@example.com', 'pass12345')
        self.other_user = User.objects.create_user('other', 'other@example.com', 'pass12345')
        self.team_a = Team.objects.create(name='Team A', fifa_code='TAA')
        self.team_b = Team.objects.create(name='Team B', fifa_code='TBB', flag_code='br')
        self.team_c = Team.objects.create(name='Team C', fifa_code='TCC')
        self.team_d = Team.objects.create(name='Team D', fifa_code='TDD')
        self.future_match = Match.objects.create(
            match_number=1,
            phase=Match.Phase.GROUP_STAGE,
            home_team=self.team_a,
            away_team=self.team_b,
            kickoff_at=timezone.now() + timedelta(days=3),
        )
        self.locked_match = Match.objects.create(
            match_number=2,
            phase=Match.Phase.GROUP_STAGE,
            home_team=self.team_c,
            away_team=self.team_d,
            kickoff_at=timezone.now() - timedelta(hours=1),
        )

    def test_tournament_invite_code_is_autogenerated(self):
        tournament = FriendTournament.objects.create(name='Admin Tournament')

        self.assertTrue(tournament.invite_code)
        self.assertEqual(len(tournament.invite_code), 8)

    def test_staff_can_create_tournament_in_admin_with_autogenerated_invite_code(self):
        staff = User.objects.create_superuser('admin', 'admin@example.com', 'pass12345')
        self.client.force_login(staff)

        response = self.client.post(reverse('admin:tournaments_friendtournament_add'), {
            'name': 'Admin Created',
            'slug': '',
            'owner': '',
            'description': '',
            'max_members': 15,
            'is_private': 'on',
            'is_active': 'on',
            'memberships-TOTAL_FORMS': '0',
            'memberships-INITIAL_FORMS': '0',
            'memberships-MIN_NUM_FORMS': '0',
            'memberships-MAX_NUM_FORMS': '1000',
        })

        self.assertEqual(response.status_code, 302)
        tournament = FriendTournament.objects.get(name='Admin Created')
        self.assertTrue(tournament.invite_code)

    def test_staff_quick_admin_creates_and_toggles_tournaments(self):
        staff = User.objects.create_superuser('staff_admin', 'staff@example.com', 'pass12345')
        self.client.force_login(staff)

        response = self.client.post(reverse('tournaments:staff_admin'), {
            'name': 'Quick Tournament',
            'owner': '',
            'description': 'Torneo desde panel rápido',
            'max_members': 15,
            'is_private': 'on',
            'is_active': 'on',
        })

        self.assertRedirects(response, reverse('tournaments:staff_admin'))
        tournament = FriendTournament.objects.get(name='Quick Tournament')
        self.assertTrue(tournament.invite_code)
        self.assertTrue(tournament.is_active)

        response = self.client.post(reverse('tournaments:staff_toggle_active', kwargs={'slug': tournament.slug}))
        self.assertRedirects(response, reverse('tournaments:staff_admin'))
        tournament.refresh_from_db()
        self.assertFalse(tournament.is_active)

    def test_staff_quick_admin_rejects_more_than_15_members(self):
        staff = User.objects.create_superuser('staff_limit', 'staff_limit@example.com', 'pass12345')
        self.client.force_login(staff)

        response = self.client.post(reverse('tournaments:staff_admin'), {
            'name': 'Too Big',
            'owner': '',
            'description': '',
            'max_members': 16,
            'is_private': 'on',
            'is_active': 'on',
        })

        self.assertEqual(response.status_code, 200)
        self.assertFalse(FriendTournament.objects.filter(name='Too Big').exists())
        self.assertContains(response, 'El máximo permitido es 15 participantes.')

    def test_regular_user_cannot_access_staff_tournament_admin(self):
        self.client.force_login(self.user)

        response = self.client.get(reverse('tournaments:staff_admin'))

        self.assertEqual(response.status_code, 302)
        self.assertIn('/admin/login/', response.url)

    def test_staff_can_trigger_fixture_update_from_panel(self):
        staff = User.objects.create_superuser('fixture_staff', 'fixture_staff@example.com', 'pass12345')
        self.client.force_login(staff)
        calls = []

        def fake_sync_fixture(days_back, days_forward):
            calls.append(('fixture', days_back, days_forward))
            return {'fixture_updated_count': 4, 'seen_count': 18}

        original_sync_fixture = views.sync_fixture
        views.sync_fixture = fake_sync_fixture
        try:
            response = self.client.post(reverse('tournaments:staff_update_fixture'))
        finally:
            views.sync_fixture = original_sync_fixture

        self.assertRedirects(response, reverse('tournaments:staff_admin'))
        self.assertEqual(calls, [('fixture', 1, 14)])

    def test_staff_can_trigger_api_result_sync_from_panel(self):
        staff = User.objects.create_superuser('sync_staff', 'sync_staff@example.com', 'pass12345')
        self.client.force_login(staff)
        calls = []

        def fake_sync_fixture(days_back, days_forward):
            calls.append(('fixture', days_back, days_forward))
            return {'fixture_updated_count': 3}

        def fake_sync_results(days_back, days_forward):
            calls.append(('sync', days_back, days_forward))
            return {'updated_count': 2, 'seen_count': 4}

        def fake_recalculate_predictions():
            calls.append(('recalculate',))
            return 5

        original_sync_fixture = views.sync_fixture
        original_sync_results = views.sync_results
        original_recalculate_predictions = views.recalculate_predictions
        views.sync_fixture = fake_sync_fixture
        views.sync_results = fake_sync_results
        views.recalculate_predictions = fake_recalculate_predictions
        try:
            response = self.client.post(reverse('tournaments:staff_sync_results'))
        finally:
            views.sync_fixture = original_sync_fixture
            views.sync_results = original_sync_results
            views.recalculate_predictions = original_recalculate_predictions

        self.assertRedirects(response, reverse('tournaments:staff_admin'))
        self.assertEqual(calls, [('fixture', 1, 14), ('sync', 1, 1), ('recalculate',)])

    def test_regular_user_cannot_trigger_staff_operations(self):
        self.client.force_login(self.user)

        fixture_response = self.client.post(reverse('tournaments:staff_update_fixture'))
        sync_response = self.client.post(reverse('tournaments:staff_sync_results'))

        self.assertEqual(fixture_response.status_code, 302)
        self.assertEqual(sync_response.status_code, 302)
        self.assertIn('/admin/login/', fixture_response.url)
        self.assertIn('/admin/login/', sync_response.url)

    def test_user_registers_logs_in_joins_and_sees_only_their_tournaments(self):
        tournament = FriendTournament.objects.create(name='Visible Tournament')
        hidden = FriendTournament.objects.create(name='Hidden Tournament')

        response = self.client.post(reverse('register'), {
            'username': 'new_player',
            'email': 'new@example.com',
            'password1': 'StrongPass123',
            'password2': 'StrongPass123',
        })
        self.assertRedirects(response, reverse('tournaments:list'))

        response = self.client.post(reverse('tournaments:join'), {'invite_code': tournament.invite_code})
        self.assertRedirects(response, tournament.get_absolute_url())
        self.assertTrue(TournamentMembership.objects.filter(tournament=tournament, user__username='new_player').exists())

        response = self.client.get(reverse('tournaments:list'))
        self.assertContains(response, tournament.name)
        self.assertNotContains(response, hidden.name)

    def test_join_tournament_blocks_when_member_limit_is_reached(self):
        tournament = FriendTournament.objects.create(name='Full Tournament', max_members=15)
        for index in range(15):
            user = User.objects.create_user(f'full_{index}', f'full_{index}@example.com', 'pass12345')
            TournamentMembership.objects.create(tournament=tournament, user=user)
        self.client.force_login(self.user)

        response = self.client.post(reverse('tournaments:join'), {'invite_code': tournament.invite_code})

        self.assertEqual(response.status_code, 200)
        self.assertFalse(TournamentMembership.objects.filter(tournament=tournament, user=self.user).exists())
        self.assertContains(response, 'El torneo ya alcanzó el máximo de 15 participantes.')

    def test_tournament_pages_require_membership(self):
        tournament = FriendTournament.objects.create(name='Private Tournament')
        self.client.force_login(self.user)

        protected_urls = [
            reverse('tournaments:detail', kwargs={'slug': tournament.slug}),
            reverse('tournaments:fixture', kwargs={'slug': tournament.slug}),
            reverse('tournaments:predictions', kwargs={'slug': tournament.slug}),
            reverse('tournaments:leaderboard', kwargs={'slug': tournament.slug}),
            reverse('tournaments:members', kwargs={'slug': tournament.slug}),
            reverse('tournaments:member_predictions', kwargs={'slug': tournament.slug, 'user_id': self.other_user.id}),
            reverse('tournaments:match_detail', kwargs={'slug': tournament.slug, 'match_id': self.future_match.id}),
        ]

        for url in protected_urls:
            with self.subTest(url=url):
                response = self.client.get(url)
                self.assertEqual(response.status_code, 403)

    def test_match_page_shows_venue_and_user_timezone(self):
        tournament = FriendTournament.objects.create(name='Timezone Tournament')
        TournamentMembership.objects.create(tournament=tournament, user=self.user)
        self.user.profile.timezone = 'America/Buenos_Aires'
        self.user.profile.save()
        self.future_match.venue = 'Mexico City Stadium'
        self.future_match.venue_timezone = 'America/Mexico_City'
        self.future_match.kickoff_at = datetime(2026, 6, 11, 19, 0, tzinfo=datetime_timezone.utc)
        self.future_match.save()
        self.client.force_login(self.user)

        response = self.client.get(reverse('tournaments:match_detail', kwargs={'slug': tournament.slug, 'match_id': self.future_match.id}))

        self.assertContains(response, 'Horario sede: 11/06/2026 13:00')
        self.assertContains(response, 'Tu horario: 11/06/2026 16:00')
        self.assertContains(response, 'fi-br')

    def test_prediction_can_be_created_and_edited_only_before_kickoff(self):
        tournament = FriendTournament.objects.create(name='Predictions Tournament')
        TournamentMembership.objects.create(tournament=tournament, user=self.user)
        self.client.force_login(self.user)

        response = self.client.post(
            reverse('tournaments:match_detail', kwargs={'slug': tournament.slug, 'match_id': self.future_match.id}),
            {'predicted_home_score': 1, 'predicted_away_score': 0},
        )
        self.assertRedirects(response, reverse('tournaments:predictions', kwargs={'slug': tournament.slug}))
        prediction = Prediction.objects.get(tournament=tournament, user=self.user, match=self.future_match)
        self.assertEqual(prediction.score_label, '1 - 0')

        response = self.client.post(
            reverse('tournaments:match_detail', kwargs={'slug': tournament.slug, 'match_id': self.future_match.id}),
            {'predicted_home_score': 2, 'predicted_away_score': 0},
        )
        self.assertRedirects(response, reverse('tournaments:predictions', kwargs={'slug': tournament.slug}))
        prediction.refresh_from_db()
        self.assertEqual(prediction.score_label, '2 - 0')

        response = self.client.post(
            reverse('tournaments:match_detail', kwargs={'slug': tournament.slug, 'match_id': self.locked_match.id}),
            {'predicted_home_score': 3, 'predicted_away_score': 0},
        )
        self.assertRedirects(response, reverse('tournaments:match_detail', kwargs={'slug': tournament.slug, 'match_id': self.locked_match.id}))
        self.assertFalse(Prediction.objects.filter(tournament=tournament, user=self.user, match=self.locked_match).exists())

    def test_bulk_predictions_save_multiple_matches_with_select_scores(self):
        tournament = FriendTournament.objects.create(name='Bulk Predictions Tournament')
        TournamentMembership.objects.create(tournament=tournament, user=self.user)
        self.client.force_login(self.user)

        response = self.client.get(reverse('tournaments:predictions', kwargs={'slug': tournament.slug}))
        self.assertContains(response, '<option value="10"', html=False)

        response = self.client.post(reverse('tournaments:predictions', kwargs={'slug': tournament.slug}), {
            f'match_{self.future_match.id}_home': '2',
            f'match_{self.future_match.id}_away': '1',
            f'match_{self.locked_match.id}_home': '3',
            f'match_{self.locked_match.id}_away': '0',
        })

        self.assertRedirects(response, reverse('tournaments:predictions', kwargs={'slug': tournament.slug}))
        prediction = Prediction.objects.get(tournament=tournament, user=self.user, match=self.future_match)
        self.assertEqual(prediction.score_label, '2 - 1')
        self.assertFalse(Prediction.objects.filter(tournament=tournament, user=self.user, match=self.locked_match).exists())

    def test_predictions_list_links_finished_results_to_group_predictions(self):
        tournament = FriendTournament.objects.create(name='Result Link Tournament')
        TournamentMembership.objects.create(tournament=tournament, user=self.user)
        Prediction.objects.create(
            tournament=tournament,
            user=self.user,
            match=self.locked_match,
            predicted_home_score=1,
            predicted_away_score=0,
        )
        self.locked_match.status = Match.Status.FINISHED
        self.locked_match.home_score = 1
        self.locked_match.away_score = 0
        self.locked_match.save()
        recalculate_predictions(tournament=tournament)
        self.client.force_login(self.user)

        response = self.client.get(reverse('tournaments:predictions', kwargs={'slug': tournament.slug}))

        self.assertEqual(response.status_code, 200)
        self.assertContains(response, reverse('tournaments:match_predictions', kwargs={
            'slug': tournament.slug,
            'match_id': self.locked_match.id,
        }))

    def test_fixture_links_finished_results_to_group_predictions(self):
        tournament = FriendTournament.objects.create(name='Fixture Result Link Tournament')
        TournamentMembership.objects.create(tournament=tournament, user=self.user)
        self.locked_match.status = Match.Status.FINISHED
        self.locked_match.home_score = 1
        self.locked_match.away_score = 0
        self.locked_match.save()
        self.client.force_login(self.user)

        response = self.client.get(reverse('tournaments:fixture', kwargs={'slug': tournament.slug}))

        self.assertEqual(response.status_code, 200)
        self.assertContains(response, reverse('tournaments:match_predictions', kwargs={
            'slug': tournament.slug,
            'match_id': self.locked_match.id,
        }))

    def test_points_and_leaderboard_are_per_tournament(self):
        tournament_a = FriendTournament.objects.create(name='Tournament A')
        tournament_b = FriendTournament.objects.create(name='Tournament B')
        TournamentMembership.objects.create(tournament=tournament_a, user=self.user)
        TournamentMembership.objects.create(tournament=tournament_a, user=self.other_user)
        TournamentMembership.objects.create(tournament=tournament_b, user=self.user)

        exact = Prediction.objects.create(tournament=tournament_a, user=self.user, match=self.future_match, predicted_home_score=2, predicted_away_score=1)
        outcome = Prediction.objects.create(tournament=tournament_a, user=self.other_user, match=self.future_match, predicted_home_score=1, predicted_away_score=0)
        wrong = Prediction.objects.create(tournament=tournament_b, user=self.user, match=self.future_match, predicted_home_score=0, predicted_away_score=3)

        self.future_match.status = Match.Status.FINISHED
        self.future_match.home_score = 2
        self.future_match.away_score = 1
        self.future_match.save()
        recalculate_predictions()

        exact.refresh_from_db()
        outcome.refresh_from_db()
        wrong.refresh_from_db()
        self.assertEqual(exact.points, 5)
        self.assertEqual(outcome.points, 2)
        self.assertEqual(wrong.points, 0)

        rows_a = leaderboard_for_tournament(tournament_a)
        rows_b = leaderboard_for_tournament(tournament_b)
        self.assertEqual([(row['user'].username, row['points']) for row in rows_a], [('player', 5), ('other', 2)])
        self.assertEqual([(row['user'].username, row['points']) for row in rows_b], [('player', 0)])

    def test_leaderboard_tracks_position_changes_after_recalculation(self):
        tournament = FriendTournament.objects.create(name='Position Changes Tournament')
        TournamentMembership.objects.create(tournament=tournament, user=self.user)
        TournamentMembership.objects.create(tournament=tournament, user=self.other_user)
        Prediction.objects.create(tournament=tournament, user=self.user, match=self.future_match, predicted_home_score=2, predicted_away_score=1)
        Prediction.objects.create(tournament=tournament, user=self.other_user, match=self.future_match, predicted_home_score=1, predicted_away_score=0)

        self.future_match.status = Match.Status.FINISHED
        self.future_match.home_score = 2
        self.future_match.away_score = 1
        self.future_match.save()
        recalculate_predictions(tournament=tournament)

        Prediction.objects.create(tournament=tournament, user=self.user, match=self.locked_match, predicted_home_score=0, predicted_away_score=1)
        Prediction.objects.create(tournament=tournament, user=self.other_user, match=self.locked_match, predicted_home_score=3, predicted_away_score=0)
        self.locked_match.status = Match.Status.FINISHED
        self.locked_match.home_score = 3
        self.locked_match.away_score = 0
        self.locked_match.save()
        recalculate_predictions(tournament=tournament)

        rows = leaderboard_for_tournament(tournament)
        self.assertEqual([(row['user'].username, row['points'], row['position_change']) for row in rows], [
            ('other', 7, 1),
            ('player', 5, -1),
        ])

    def test_member_prediction_detail_for_regular_user_only_shows_scored_finished_matches(self):
        tournament = FriendTournament.objects.create(name='Visible Predictions Tournament')
        TournamentMembership.objects.create(tournament=tournament, user=self.user)
        TournamentMembership.objects.create(tournament=tournament, user=self.other_user)
        future_prediction = Prediction.objects.create(
            tournament=tournament,
            user=self.other_user,
            match=self.future_match,
            predicted_home_score=4,
            predicted_away_score=4,
        )
        finished_prediction = Prediction.objects.create(
            tournament=tournament,
            user=self.other_user,
            match=self.locked_match,
            predicted_home_score=1,
            predicted_away_score=0,
        )
        self.locked_match.status = Match.Status.FINISHED
        self.locked_match.home_score = 1
        self.locked_match.away_score = 0
        self.locked_match.save()
        recalculate_predictions(tournament=tournament)
        finished_prediction.refresh_from_db()
        future_prediction.refresh_from_db()
        self.client.force_login(self.user)

        response = self.client.get(reverse('tournaments:member_predictions', kwargs={
            'slug': tournament.slug,
            'user_id': self.other_user.id,
        }))

        self.assertEqual(response.status_code, 200)
        self.assertContains(response, 'Pronósticos de other')
        self.assertContains(response, '1 - 0')
        self.assertContains(response, '5')
        self.assertContains(response, reverse('tournaments:match_predictions', kwargs={
            'slug': tournament.slug,
            'match_id': self.locked_match.id,
        }))
        self.assertNotContains(response, '4 - 4')

    def test_match_predictions_show_group_predictions_for_finished_match(self):
        tournament = FriendTournament.objects.create(name='Match Predictions Tournament')
        third_user = User.objects.create_user('third', 'third@example.com', 'pass12345')
        TournamentMembership.objects.create(tournament=tournament, user=self.user)
        TournamentMembership.objects.create(tournament=tournament, user=self.other_user)
        TournamentMembership.objects.create(tournament=tournament, user=third_user)
        exact = Prediction.objects.create(
            tournament=tournament,
            user=self.user,
            match=self.locked_match,
            predicted_home_score=1,
            predicted_away_score=0,
        )
        outcome = Prediction.objects.create(
            tournament=tournament,
            user=self.other_user,
            match=self.locked_match,
            predicted_home_score=2,
            predicted_away_score=0,
        )
        self.locked_match.status = Match.Status.FINISHED
        self.locked_match.home_score = 1
        self.locked_match.away_score = 0
        self.locked_match.save()
        recalculate_predictions(tournament=tournament)
        exact.refresh_from_db()
        outcome.refresh_from_db()
        self.client.force_login(self.user)

        response = self.client.get(reverse('tournaments:match_predictions', kwargs={
            'slug': tournament.slug,
            'match_id': self.locked_match.id,
        }))

        self.assertEqual(response.status_code, 200)
        self.assertContains(response, 'Pronósticos del grupo')
        self.assertContains(response, 'player')
        self.assertContains(response, 'other')
        self.assertContains(response, 'third')
        self.assertContains(response, '1 - 0')
        self.assertContains(response, '2 - 0')
        self.assertContains(response, 'Sin pronóstico')
        self.assertContains(response, '5')
        self.assertContains(response, '2')

    def test_match_predictions_require_finished_result(self):
        tournament = FriendTournament.objects.create(name='Hidden Match Predictions Tournament')
        TournamentMembership.objects.create(tournament=tournament, user=self.user)
        self.client.force_login(self.user)

        response = self.client.get(reverse('tournaments:match_predictions', kwargs={
            'slug': tournament.slug,
            'match_id': self.future_match.id,
        }))

        self.assertEqual(response.status_code, 403)

    def test_member_prediction_detail_for_staff_shows_future_matches(self):
        staff = User.objects.create_superuser('staff_viewer', 'staff_viewer@example.com', 'pass12345')
        tournament = FriendTournament.objects.create(name='Staff Visible Predictions Tournament')
        TournamentMembership.objects.create(tournament=tournament, user=staff)
        TournamentMembership.objects.create(tournament=tournament, user=self.other_user)
        Prediction.objects.create(
            tournament=tournament,
            user=self.other_user,
            match=self.future_match,
            predicted_home_score=4,
            predicted_away_score=4,
        )
        self.client.force_login(staff)

        response = self.client.get(reverse('tournaments:member_predictions', kwargs={
            'slug': tournament.slug,
            'user_id': self.other_user.id,
        }))

        self.assertEqual(response.status_code, 200)
        self.assertContains(response, '4 - 4')

    def test_seed_does_not_schedule_same_team_twice_on_same_day(self):
        Match.objects.all().delete()
        Team.objects.all().delete()
        SeedWorldCupCommand().handle()

        appearances = set()
        for match in Match.objects.filter(phase=Match.Phase.GROUP_STAGE).select_related('home_team', 'away_team'):
            match_day = match.kickoff_at.date()
            for team in [match.home_team, match.away_team]:
                key = (team_id := team.id, match_day)
                self.assertNotIn(key, appearances, f'{team.name} aparece dos veces el {match_day}')
                appearances.add((team_id, match_day))

    def test_seed_sets_argentina_austria_at_14_argentina_time(self):
        Match.objects.all().delete()
        Team.objects.all().delete()
        SeedWorldCupCommand().handle()

        match = Match.objects.get(match_number=41, home_team__name='Argentina', away_team__name='Austria')
        argentina_time = match.kickoff_at.astimezone(ZoneInfo('America/Buenos_Aires'))

        self.assertEqual(match.venue, 'AT&T Stadium')
        self.assertEqual(match.venue_timezone, 'America/Chicago')
        self.assertEqual(argentina_time.strftime('%Y-%m-%d %H:%M'), '2026-06-22 14:00')

    def test_seed_sets_australia_turkiye_at_01_argentina_time(self):
        Match.objects.all().delete()
        Team.objects.all().delete()
        SeedWorldCupCommand().handle()

        match = Match.objects.get(match_number=8, home_team__name='Australia', away_team__name='Türkiye')
        argentina_time = match.kickoff_at.astimezone(ZoneInfo('America/Buenos_Aires'))
        venue_time = match.kickoff_at.astimezone(ZoneInfo(match.venue_timezone))

        self.assertEqual(match.venue, 'BC Place')
        self.assertEqual(match.venue_timezone, 'America/Vancouver')
        self.assertEqual(argentina_time.strftime('%Y-%m-%d %H:%M'), '2026-06-14 01:00')
        self.assertEqual(venue_time.strftime('%Y-%m-%d %H:%M'), '2026-06-13 21:00')

    def test_seed_preserves_confirmed_knockout_teams(self):
        Match.objects.all().delete()
        Team.objects.all().delete()
        SeedWorldCupCommand().handle()
        south_africa = Team.objects.get(name='South Africa')
        canada = Team.objects.get(name='Canada')
        match = Match.objects.get(match_number=73)
        match.home_team = south_africa
        match.away_team = canada
        match.home_team_placeholder = ''
        match.away_team_placeholder = ''
        match.save(update_fields=['home_team', 'away_team', 'home_team_placeholder', 'away_team_placeholder', 'updated_at'])

        SeedWorldCupCommand().handle()

        match.refresh_from_db()
        self.assertEqual(match.home_team, south_africa)
        self.assertEqual(match.away_team, canada)
        self.assertEqual(match.home_team_placeholder, '')
        self.assertEqual(match.away_team_placeholder, '')

    def test_thesportsdb_sync_updates_finished_result(self):
        self.future_match.external_id = 'thesportsdb:fixture-1'
        self.future_match.save(update_fields=['external_id'])

        def fake_fetch_events_for_day(day):
            return 'fake-endpoint', [{
                'idEvent': 'fixture-1',
                'strHomeTeam': 'Team A',
                'strAwayTeam': 'Team B',
                'intHomeScore': '2',
                'intAwayScore': '1',
            }]

        def fake_fetch_events_for_season():
            return 'fake-season-endpoint', []

        def fake_fetch_events_by_name(home_name, away_name):
            return 'fake-search-endpoint', []

        original_fetch = thesportsdb._fetch_events_for_day
        original_fetch_season = thesportsdb._fetch_events_for_season
        original_fetch_by_name = thesportsdb._fetch_events_by_name
        thesportsdb._fetch_events_for_day = fake_fetch_events_for_day
        thesportsdb._fetch_events_for_season = fake_fetch_events_for_season
        thesportsdb._fetch_events_by_name = fake_fetch_events_by_name
        try:
            result = thesportsdb.sync_results(days_back=0, days_forward=0, use_fifa_fallback=False)
        finally:
            thesportsdb._fetch_events_for_day = original_fetch
            thesportsdb._fetch_events_for_season = original_fetch_season
            thesportsdb._fetch_events_by_name = original_fetch_by_name

        self.future_match.refresh_from_db()
        self.assertEqual(result['updated_count'], 1)
        self.assertEqual(self.future_match.status, Match.Status.FINISHED)
        self.assertEqual(self.future_match.home_score, 2)
        self.assertEqual(self.future_match.away_score, 1)

# Create your tests here.
