# Generated by Django 5.2.8 on 2026-05-12 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(choices=[('America/Buenos_Aires', 'Argentina'), ('America/Mexico_City', 'Ciudad de México'), ('America/Toronto', 'Toronto / Este'), ('America/New_York', 'Nueva York / Este'), ('America/Chicago', 'Centro USA'), ('America/Denver', 'Montaña USA'), ('America/Los_Angeles', 'Pacífico USA'), ('America/Vancouver', 'Vancouver'), ('Europe/Madrid', 'España'), ('UTC', 'UTC')], default='America/Buenos_Aires', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
