# Generated by Django 5.2.8 on 2026-05-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendtournament',
            name='max_members',
            field=models.PositiveSmallIntegerField(default=15),
        ),
    ]
