# Generated by Django 5.2.8 on 2026-05-12 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='flag_code',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
