# Generated by Django 5.2.8 on 2026-05-12 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_team_flag_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='display_name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
