# Generated by Django 5.2.8 on 2026-05-12 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=80)),
                ('endpoint', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=40)),
                ('request_count', models.PositiveIntegerField(default=0)),
                ('response_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('match_number', models.PositiveSmallIntegerField(unique=True)),
                ('phase', models.CharField(choices=[('group_stage', 'Fase de grupos'), ('round_of_32', '16avos de final'), ('round_of_16', 'Octavos de final'), ('quarter_final', 'Cuartos de final'), ('semi_final', 'Semifinal'), ('third_place', 'Tercer puesto'), ('final', 'Final')], max_length=30)),
                ('home_team_placeholder', models.CharField(blank=True, max_length=120)),
                ('away_team_placeholder', models.CharField(blank=True, max_length=120)),
                ('kickoff_at', models.DateTimeField()),
                ('venue', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(choices=[('scheduled', 'Programado'), ('live', 'En vivo'), ('finished', 'Finalizado'), ('postponed', 'Postergado'), ('cancelled', 'Cancelado')], default='scheduled', max_length=20)),
                ('home_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('away_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('away_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='away_matches', to='teams.team')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='teams.worldcupgroup')),
                ('home_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_matches', to='teams.team')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to='teams.team')),
            ],
            options={
                'ordering': ['kickoff_at', 'match_number'],
            },
        ),
    ]
