# Generated by Django 5.2.8 on 2026-05-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='venue_timezone',
            field=models.CharField(default='UTC', max_length=80),
        ),
    ]
